# GitHub Actions ile sitemizi GitHub Pages'e deploy etmek için basit bir workflow

name: Deploy GitHub Pages site

on:
  # main branch'ine yapılan her push işleminde çalışır
  push:
    branches: ["main"]

  # Actions sekmesinden manuel olarak çalıştırmanıza da olanak tanır
  workflow_dispatch:

# GITHUB_TOKEN için izinleri ayarla
permissions:
  contents: read
  pages: write
  id-token: write

# Aynı anda sadece bir deploy işleminin çalışmasına izin ver
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Tek deploy işi
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Kullandığınız Node.js sürümünü yazabilirsiniz
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # dist klasörünü yükle
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4